[Issue-69] [Issue-107] Update UX home page and import account page
Koniverse/SubWallet-Extension pull request #112
Opened 2022-04-05 06:47 UTC by S2kael

### Related issue

- #69 
- #107 

### Is your feature request related to a problem? Please describe.

- Update Import Account screen UX
- Update Home screen UX

### Describe the solution you'd like

- Change clickable of crypto info from all area to left area only
- Add smooth scrolling when crypto details are obscured
- Fix jerky with/without vertical scrollbar (change overflow from auto to overlay)
- Reset password and error when change json file

### Describe alternatives you've considered
No

### Additional context
No

2022-04-05 07:45 UTC, lw-cdm requested changes

2022-04-05 07:45 UTC, lw-cdm commented on packages/extension-koni-ui/src/util/dom.ts
> +// [object Object]
![image](https://user-images.githubusercontent.com/92499846/161699000-51a58053-3c7d-4b04-9042-4dcfcbc8780e.png)
Incorrect header. Please run "yarn lint" for more details

2022-04-05 07:45 UTC, lw-cdm commented on packages/extension-koni-ui/src/util/dom.ts
> +  const poops = setInterval(function () {
Change "poops" to another word.
Search Google for knowing what "poops" means.

2022-04-05 07:45 UTC, lw-cdm commented on packages/extension-koni-ui/src/Popup/Home/index.tsx
> +    overflow: overlay;
"overlay" does not work on Firefox. Please find another solution.
![image](https://user-images.githubusercontent.com/92499846/161703449-c530da5b-4dc7-4983-8afb-fff6f41d8675.png)

2022-04-05 07:45 UTC, lw-cdm commented on packages/extension-koni-ui/src/util/dom.ts
> +// [object Object]
incorrect header when run yarn lint
![image](https://user-images.githubusercontent.com/92499846/161703861-71889406-f5fb-48a8-8f25-8030d6edb906.png)

2022-04-05 07:45 UTC, lw-cdm commented on packages/extension-koni-ui/src/util/dom.ts
> +  const poops = setInterval(function () {
change "poops" to another word. Do you know what the word mean ?

2022-04-05 07:45 UTC, lw-cdm commented on packages/extension-koni-ui/src/Popup/Home/ChainBalances/ChainBalanceDetail/ChainBalanceDetailItem.tsx
> +  }, [accountInfo.networkKey, toggleBalanceDetail, isShowDetail]);
error when run yarn lint
![image](https://user-images.githubusercontent.com/92499846/161704379-e1b562cc-ab4d-4788-a9ab-ef81867c5ef7.png)

2022-04-05 08:49 UTC, sokol142 reviewed
Still display message wrong password when change file. 
![image](https://user-images.githubusercontent.com/102292476/161713741-909984dd-c565-40f7-b07a-b996bd9eab46.png)

2022-04-05 09:43 UTC, S2kael commented
> Still display message wrong password when change file. ![image](https://user-images.githubusercontent.com/102292476/161713741-909984dd-c565-40f7-b07a-b996bd9eab46.png)

Fixed

2022-04-06 03:14 UTC, lw-cdm approved these changes
ok

2022-04-06 03:17 UTC, merged