[Issue 2330] Extension - Add T&C for extension and webapp
Koniverse/SubWallet-Extension pull request #2379
Opened 2023-12-19 07:32 UTC by Thiendekaco

Describe the task
Add T&C for extension and webapp

Link doc: https://www.notion.so/subwallet/SubWallet-Th-m-T-C-cho-ng-d-ng-243dabfe04f74347bfc400277655485d?pvs=4

2023-12-19 07:39 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-2379--sw-web-runner.netlify.app

2023-12-20 10:43 UTC, lw-cdm approved these changes

2023-12-26 11:45 UTC, lw-cdm approved these changes

2023-12-28 12:45 UTC, saltict requested changes
Please fix my comment

2023-12-28 12:45 UTC, saltict commented on packages/extension-koni-ui/src/Popup/Keyring/ChangePassword.tsx
> +                I understand that SubWallet can’t recover the password. <a
Require i18n this sentence

2023-12-29 02:21 UTC, saltict approved these changes

2023-12-29 02:21 UTC, merged