[Issue-2447] Update chainlist
Koniverse/SubWallet-Extension pull request #2448
Opened 2024-01-04 11:05 UTC by bluezdot

### Related issue(s)
#2447 

### Is your feature request related to a problem(s)? Please describe.

- Update new logic for earning

### Describe the solution you'd like

- Temporarily blocking ARCH token transfer.
- Check VARCH balances, cDOT-7/14 balances.
- Check parallel provider (Dwellir).

### Describe alternatives you've considered

- No

### Additional context

- No

2024-01-04 11:12 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-2448--sw-web-runner.netlify.app

2024-01-04 11:40 UTC, nampc1 requested changes

2024-01-04 11:40 UTC, nampc1 commented on packages/extension-base/src/koni/api/dotsama/transfer.ts
> +    if (networkKey === 'invarch') {
Move this to the transfer checking function

2024-01-04 12:08 UTC, nampc1 commented on package.json
> +    "@subwallet/chain-list": "0.2.34-beta.2",
missing DOT logo, check again

2024-01-05 03:14 UTC, nampc1 approved these changes

2024-01-05 03:14 UTC, nampc1 commented on packages/extension-base/src/koni/api/dotsama/transfer.ts
> +    if (networkKey === 'invarch') {
The checking function is deprecated

2024-01-05 03:14 UTC, nampc1 commented on package.json
> +    "@subwallet/chain-list": "0.2.34-beta.2",
fixed in Chainlist v0.2.34-beta.3

2024-01-05 09:53 UTC, saltict approved these changes

2024-01-05 09:53 UTC, merged