[Issue-2513] Add apy for manta collators
Koniverse/SubWallet-Extension pull request #2686
Opened 2024-03-02 04:45 UTC by bluezdot

### Related issue(s)
#2513 

### Is your feature request related to a problem(s)? Please describe.

- Update APY formula for Manta collators

### Describe the solution you'd like

- https://gist.github.com/Dengjianping/c5286c3f5a237a8ac206043e9291009e
- https://hackmd.io/@_Q2DC8MwRu2akXdRJqor8A/Hy1lsVAKp

### Describe alternatives you've considered

- No

### Additional context

- No

2024-03-02 04:54 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-2686--sw-web-runner.netlify.app

2024-03-07 05:12 UTC, nampc1 requested changes

2024-03-07 05:12 UTC, nampc1 commented on packages/extension-base/src/services/earning-service/handlers/native-staking/para-chain.ts
> +          const _collatorPoints = await apiProps.api.query.parachainStaking.awardedPts(parseInt(round.current) - 1, collatorAddress);
should not await in a for loop, this will affect performance

2024-03-07 08:11 UTC, nampc1 approved these changes

2024-03-08 07:58 UTC, saltict approved these changes

2024-03-08 07:58 UTC, merged