[Issue-2934] Support nfts pallet NFT on statemine
Koniverse/SubWallet-Extension pull request #2936
Opened 2024-04-17 12:46 UTC by bluezdot

### Related issue(s)

- #2934 

### Is your feature request related to a problem(s)? Please describe.

- Support nfts pallet NFT on statemine

### Describe the solution you'd like

- Support nfts pallet NFT on statemine

### Describe alternatives you've considered

- No

### Additional context

- No

2024-04-18 03:16 UTC, nampc1 approved these changes

2024-04-18 04:41 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-2936--sw-web-runner.netlify.app

2024-04-18 04:43 UTC, nampc1 requested changes

2024-04-18 04:43 UTC, nampc1 commented on packages/extension-base/src/background/KoniTypes.ts
> +  assetHubType?: AssetHubNftType
should bring all optional data to a new interface

2024-04-18 04:43 UTC, nampc1 commented on packages/extension-base/src/koni/api/nft/transfer.ts
> +    if (nftType === AssetHubNftType.NFTS) {
should merge with the previous function to avoid duplication

2024-04-18 05:04 UTC, nampc1 approved these changes

2024-04-19 11:56 UTC, saltict approved these changes

2024-04-19 11:56 UTC, merged