[Issue-2512] Research swap pallet on asset hub
Koniverse/SubWallet-Extension pull request #3196
Opened 2024-06-13 07:21 UTC by S2kael

### Related issue(s)

- #2512

### Is your feature request related to a problem(s)? Please describe.

- Integration with swap protocol on Asset Hub

### Describe the solution you'd like

- Integration with swap protocol on Asset Hub

### Describe alternatives you've considered

- No

### Additional context

- No

2024-06-13 08:38 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3196--sw-web-runner.netlify.app

2024-06-18 04:16 UTC, nampc1 requested changes

2024-06-18 04:16 UTC, nampc1 commented on packages/extension-base/src/services/swap-service/handler/asset-hub/utils.ts
> +    const tmp = await getReserveForPool(api, asset1, asset2);
consider Promise.all

2024-06-18 04:16 UTC, nampc1 commented on packages/extension-base/src/services/swap-service/handler/asset-hub/utils.ts
> +export const checkLiquidityForPool = (amount: string, reserve1: string, reserve2: string): SwapErrorType | undefined => {
need to also check for low liquidity

2024-06-27 07:48 UTC, merged