Extension - Add validate account in case sign transaction with Ledger account
Koniverse/SubWallet-Extension pull request #3278
Opened 2024-07-03 10:55 UTC by Thiendekaco

2024-07-04 04:58 UTC, S2kael requested changes

2024-07-04 04:58 UTC, S2kael commented on packages/extension-koni-ui/src/hooks/ledger/useLedger.ts
> +      const addressOnCurrentLedger = await ledger.getAddress(false, accountOffset, addressOffset);
Add `accountOption`

2024-07-04 04:58 UTC, S2kael commented on packages/extension-koni-ui/src/hooks/ledger/useLedger.ts
> +      if (addressOnCurrentLedger.address !== address) {
Replace with deep compare(`isSameAddress`), `addressOnCurrentLedger` can be in network format

2024-07-04 04:58 UTC, S2kael commented on packages/extension-koni-ui/src/hooks/ledger/useLedger.ts
> +
Same as above

2024-07-04 05:37 UTC, S2kael approved these changes

2024-07-04 07:48 UTC, S2kael approved these changes

2024-07-04 08:15 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3278--sw-web-runner.netlify.app

2024-07-11 09:17 UTC, saltict approved these changes

2024-07-11 09:17 UTC, merged