[Issue 3307] [feature] Extension - Allow to use Migration Polkadot Appp to attach Ledger account
Koniverse/SubWallet-Extension pull request #3346
Opened 2024-07-16 12:59 UTC by Thiendekaco

2024-07-16 14:04 UTC, S2kael requested changes

2024-07-16 14:04 UTC, S2kael commented on packages/extension-koni-ui/src/Popup/Confirmations/parts/Sign/Substrate.tsx
> +    warning: ledgerWarning } = useLedger(chainSlug, activeLedger, true, isRuntimeUpdated || isMessage || !!account.slip44, account.slip44);
Remove `!!account.slip44` condition

2024-07-16 14:49 UTC, S2kael requested changes

2024-07-16 14:49 UTC, S2kael commented on packages/extension-koni-ui/src/connector/Ledger/SubstrateGenericLedger.ts
> +      const { address, pubKey } = await this.wrapError(app.getAddress(path, def?.ss58_addr_type || 42, confirm));
Replace `||` by `??`

2024-07-16 22:58 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3346--sw-web-runner.netlify.app

2024-07-17 03:15 UTC, S2kael commented on packages/extension-koni-ui/src/hooks/ledger/useLedger.ts
> +const retrieveLedger = (slugApp: string, ledgerChains: LedgerNetwork[], migrateLedgerChains: MigrationLedgerNetwork[], isEthereumNetwork: boolean, forceMigration: boolean, slugNetwork?: string): Ledg
`chainSlug` not `slugApp`

2024-07-17 03:15 UTC, S2kael commented on packages/extension-koni-ui/src/constants/ledger.ts
>    {
Sorry, but please rollbacks change, hide option instead remove

2024-07-17 03:15 UTC, S2kael commented on packages/extension-koni-ui/src/constants/ledger.ts
> +export const PredefinedMigrationLedgerNetwork: MigrationLedgerNetwork[] = [
Please update this list

2024-07-18 09:57 UTC, S2kael approved these changes

2024-07-23 08:15 UTC, S2kael commented on packages/extension-koni-ui/src/Popup/Confirmations/index.tsx
> +              if (isRawPayload(payload)) {
No need to check if `payload` is a message, this condition is checked before

2024-07-23 08:18 UTC, S2kael commented on packages/extension-koni-ui/src/hooks/ledger/useLedger.ts
> +const retrieveLedger = (chainSlug: string, ledgerChains: LedgerNetwork[], migrateLedgerChains: MigrationLedgerNetwork[], isEthereumNetwork: boolean, forceMigration: boolean, slugNetwork?: string | nu
Change name of `slugNetwork`

2024-07-30 07:48 UTC, merged