Extension - Do not show Signature popup in case not enough balance to cover gas fee
Koniverse/SubWallet-Extension pull request #3382
Opened 2024-07-24 12:33 UTC by Thiendekaco

2024-07-24 12:42 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3382--sw-web-runner.netlify.app

2024-07-30 04:27 UTC, S2kael requested changes

2024-07-30 04:27 UTC, S2kael commented on packages/extension-base/src/services/transaction-service/index.ts
> +    if (!transaction.errors || transaction.errors.length === 0) {
Why have this logic?

2024-07-30 04:27 UTC, S2kael commented on packages/extension-base/src/core/logic-validation/request.ts
> +  pair?: KeyringPair,
Make it required

2024-07-30 08:13 UTC, S2kael approved these changes

2024-07-30 11:06 UTC, S2kael requested changes

2024-07-30 11:06 UTC, S2kael commented on packages/extension-base/src/core/logic-validation/request.ts
> +  const isToContract = !hasError && await isContractAddress(transaction.to || '', evmApi);
Is only network error will make this line stuck?

2024-07-31 04:48 UTC, S2kael requested changes

2024-07-31 04:48 UTC, S2kael commented on packages/extension-base/src/background/KoniTypes.ts
> +  errorConnectNetwork: [ConfirmationsQueueItem<PayloadValidated>, ConfirmationResult<null>]
Create new type for this request, make it detailed

2024-07-31 04:48 UTC, S2kael commented on packages/extension-base/src/core/logic-validation/request.ts
> +export async function validationEvmSignMessageMiddleware (koni: KoniState, url: string, payload_: PayloadValidated, validationMiddlewareSteps: ValidateStepFunction[]): Promise<PayloadValidated> {
Remove `validationMiddlewareSteps`

2024-07-31 04:48 UTC, S2kael commented on packages/extension-base/src/services/transaction-service/index.ts
> +      // Add Transaction
Move this to `fillTransactionDefaultInfo`

2024-07-31 04:48 UTC, S2kael commented on packages/extension-base/src/services/transaction-service/index.ts
> +    const hasError = !!(payload.errors && payload.errors.length > 0);
Can remove this

2024-07-31 04:48 UTC, S2kael commented on packages/extension-koni-ui/src/Popup/Confirmations/index.tsx
> +const ERROR_CONFIRMATION_TYPE = ['errorConnectNetwork'];
Declare more specifically, type cast

2024-07-31 04:48 UTC, S2kael commented on packages/extension-koni-ui/src/Popup/Confirmations/parts/Sign/Evm.tsx
>    const { error: ledgerError,
Add logic to prevent ledger connections

2024-07-31 08:36 UTC, S2kael commented on packages/extension-base/src/background/KoniTypes.ts
> +  errors: Error[]
Does data transfer to UI success?

2024-07-31 08:36 UTC, S2kael commented on packages/extension-base/src/services/transaction-service/index.ts
> +    const transactionId = useTransactionId ? transaction.id : getTransactionId(transaction.chainType, transaction.chain, isInternal, isWalletConnectRequest(transaction.id));
Must have `useTransactionId`?

2024-08-02 03:24 UTC, S2kael approved these changes

2024-08-08 09:12 UTC, S2kael approved these changes

2024-08-16 03:05 UTC, saltict approved these changes

2024-08-16 03:05 UTC, merged