[Issue 3363] Extension -  Update connector version
Koniverse/SubWallet-Extension pull request #3437
Opened 2024-08-09 03:41 UTC by Thiendekaco

2024-08-09 03:50 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3437--sw-web-runner.netlify.app

2024-08-12 12:30 UTC, S2kael requested changes

2024-08-12 12:30 UTC, S2kael commented on packages/extension-base/src/services/wallet-connect-service/index.ts
> +    if (!(await this.haveData())) {
Why need?

2024-08-12 12:30 UTC, S2kael commented on packages/extension-base/src/services/wallet-connect-service/index.ts
> +      const sessionAccounts = requestSession.namespaces.eip155.accounts.map((account) => account.split(':')[2]);
Substrate cannot use this event?

2024-08-12 12:30 UTC, S2kael commented on packages/extension-base/src/koni/background/handlers/Tabs.ts
> +  private async revokePermissions (url: string, id: string, { params }: RequestArguments) {
Defined list permission can revoke

2024-08-12 12:30 UTC, S2kael commented on packages/extension-base/src/koni/background/handlers/Tabs.ts
> +              delete value[urlStripped];
Handle case domain have both evm and substrate authorized permission

2024-08-12 12:30 UTC, S2kael commented on packages/extension-base/src/koni/background/handlers/Tabs.ts
> +    const permissions = Object.keys(params[0] as Record<string, any>);
Standardize data, filter duplicates

2024-08-12 12:30 UTC, S2kael commented on packages/extension-base/src/koni/background/handlers/Tabs.ts
>              result.unshift(address);
Why remove this line?

2024-08-13 09:00 UTC, S2kael requested changes

2024-08-13 09:00 UTC, S2kael commented on packages/extension-base/src/koni/background/handlers/Tabs.ts
> +                  break;
missing change type

2024-08-13 09:00 UTC, S2kael commented on packages/extension-base/src/koni/background/handlers/Tabs.ts
> +    const permissions = Object.keys(params[0] as Record<string, any>).filter((permission) => {
Simpler with `Set`

2024-08-13 09:00 UTC, S2kael commented on packages/extension-base/src/koni/background/handlers/Tabs.ts
> +    const revokePermissions: Record<string, boolean> = {
Is it necessary to have a default value?

2024-08-16 07:19 UTC, S2kael approved these changes

2024-08-21 04:20 UTC, S2kael approved these changes

2024-08-27 04:14 UTC, merged