Koni/dev/issue 2751
Koniverse/SubWallet-Extension pull request #3571
Opened 2024-09-09 04:06 UTC by tunghp2002

2024-09-09 10:40 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3571--sw-web-runner.netlify.app

2024-09-11 11:38 UTC, nampc1 requested changes

2024-09-11 11:38 UTC, nampc1 commented on packages/extension-base/src/services/earning-service/handlers/native-staking/para-chain.ts
> +    const [_allCollators, _collatorCommission, _selectedCandidates] = await Promise.all([
remove this code

2024-09-11 11:38 UTC, nampc1 commented on packages/extension-base/src/koni/api/nft/ternoa_nft/index.ts
> +      const nftEntities = result?.data?.nftEntities?.nodes;
should have an interface instead of suppressing eslint errors

2024-09-11 11:38 UTC, nampc1 commented on packages/extension-base/src/services/chain-service/constants.ts
> +  ternoa: ['ternoa']
missing Ternoa testnet

2024-09-11 11:38 UTC, nampc1 commented on packages/extension-base/src/koni/api/nft/ternoa_nft/index.ts
> +        throw new Error(`HTTP error! Status: ${response.status}`);
Do not throw error, handle it silently

2024-09-11 11:38 UTC, nampc1 commented on packages/extension-base/src/koni/api/nft/ternoa_nft/index.ts
> +                        owner: { equalTo: "${address}" }
recheck with different address format. Substrate has many address formats

2024-09-12 02:25 UTC, bluezdot commented on packages/extension-base/src/services/earning-service/handlers/native-staking/para-chain.ts
> +      if (selectedCollators.includes(collatorAddress)) {
also recheck this for manta staking `allCollators.push({...`

2024-10-28 10:40 UTC, nampc1 approved these changes

2024-10-31 11:13 UTC, nampc1 approved these changes

2024-11-19 02:19 UTC, merged