Koni/dev/issue 2505 v2
Koniverse/SubWallet-Extension pull request #3587
Opened 2024-09-11 09:13 UTC by tunghp2002

2024-09-23 03:17 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3587--sw-web-runner.netlify.app

2024-09-24 03:22 UTC, nampc1 requested changes

2024-09-24 03:22 UTC, nampc1 commented on packages/extension-base/src/services/earning-service/handlers/native-staking/tao.ts
> +    } else {
should separate testnet from mainnet logic

2024-09-25 02:30 UTC, tunghp2002 commented on packages/extension-base/src/services/earning-service/handlers/native-staking/tao.ts
> +  async parseNominatorMetadata (chainInfo: _ChainInfo, address: string, delegatorState: TaoStakingStakeOption[]): Promise<Omit<YieldPositionInfo, keyof BaseYieldPositionInfo>> {
I think using Omit will help us avoid duplicating data which already had in subcribePoolPosition

2024-09-27 11:06 UTC, nampc1 approved these changes

2024-10-10 08:49 UTC, merged