[Issue-3583] Unified account - Some UI bugs for Send TON
Koniverse/SubWallet-Extension pull request #3673
Opened 2024-09-23 10:51 UTC by dungnguyen-art

Related issue: #3583

2024-09-26 04:22 UTC, nampc1 requested changes

2024-09-26 04:22 UTC, nampc1 commented on packages/extension-base/src/services/history-service/subscan-history.ts
> +    from: extrinsicItem.account_display.address,
what format is this in?

2024-09-26 04:22 UTC, nampc1 commented on packages/extension-base/src/services/history-service/subscan-history.ts
> +  const networkPrefix = chainInfo.substrateInfo?.addressPrefix ?? 42;
use util instead of direct access

2024-09-26 05:08 UTC, S2kael requested changes

2024-09-26 05:08 UTC, S2kael commented on packages/extension-base/src/services/history-service/subscan-history.ts
>      direction: isSameAddress(address, from) ? TransactionDirection.SEND : TransactionDirection.RECEIVED,
Change `from` to `transferItem.from`

2024-09-26 05:08 UTC, S2kael commented on packages/extension-koni-ui/src/components/Field/Earning/EarningPoolSelector.tsx
> +          <AccountProxyAvatar
Confirm this change with BA team

2024-09-26 08:02 UTC, dungnguyen-art commented on packages/extension-base/src/services/history-service/subscan-history.ts
> +    from: extrinsicItem.account_display.address,
it is the format of the network address

2024-09-26 11:13 UTC, lw-cdm commented on packages/extension-koni-ui/src/components/MetaInfo/parts/AccountItem.tsx
> +  console.log('account', account);
remove comment

2024-09-27 03:29 UTC, S2kael approved these changes

2024-09-27 03:29 UTC, S2kael commented on packages/extension-base/src/utils/account/common.ts
> +import { tonAddressInfo } from '@subwallet/extension-base/services/balance-service/helpers/subscribe/ton/utils';
Remove this line

2024-09-27 03:42 UTC, lw-cdm commented on packages/extension-koni-ui/src/components/Field/AddressInput.tsx
> +import { AccountProxyAvatar } from '@subwallet/extension-koni-ui/components';
Revert this file

2024-09-27 03:44 UTC, lw-cdm commented on packages/extension-koni-ui/src/components/MetaInfo/parts/TransferItem.tsx
> +    const originAddress = reformatAddress(address, 42);
no need reformat

2024-09-27 03:46 UTC, lw-cdm commented on packages/extension-koni-ui/src/Popup/Transaction/variants/SendFund.tsx
recheck this logic

2024-09-27 03:48 UTC, lw-cdm commented on packages/extension-koni-ui/src/components/Modal/AddressBook/AddressBookModal.tsx
> +        avatarValue={item.proxyId || item.formatedAddress}
change to item.address

2024-09-27 04:12 UTC, merged