[Issue-3515] Notification service
Koniverse/SubWallet-Extension pull request #3687
Opened 2024-09-26 11:17 UTC by bluezdot

2024-10-12 07:32 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3687--sw-web-runner.netlify.app

2024-10-14 10:12 UTC, S2kael requested changes

2024-10-14 10:12 UTC, S2kael commented on packages/extension-koni-ui/src/Popup/Home/index.tsx
> +            showNotificationIcon
Remove search icon?

2024-10-14 10:35 UTC, bluezdot commented on packages/extension-koni-ui/src/Popup/Home/index.tsx
> +            showNotificationIcon
request from BA, design

2024-10-16 04:56 UTC, S2kael commented on packages/extension-koni-ui/src/components/Layout/base/Home.tsx
> +    navigate('/settings/notification');
No change, confirmed with BA

2024-10-16 05:21 UTC, S2kael commented on packages/extension-koni-ui/src/components/Layout/base/Home.tsx
> +          <div className={'notification-icon'}>
Must restyle too much, not change component

2024-10-18 10:37 UTC, S2kael requested changes

2024-10-18 10:37 UTC, S2kael commented on packages/extension-base/src/services/inapp-notification-service/index.ts
> +      await fetchLastestRemindNotificationTime()
Fetching everytime?

2024-10-25 09:04 UTC, merged