[Issue - 3609] Extension - Do not show NFT Moonbeam
Koniverse/SubWallet-Extension pull request #3730
Opened 2024-10-02 02:56 UTC by tunghp2002

2024-10-02 03:08 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3730--sw-web-runner.netlify.app

2024-10-02 03:20 UTC, nampc1 requested changes

2024-10-02 03:20 UTC, nampc1 commented on packages/extension-koni-ui/src/Popup/Home/Nfts/NftImport.tsx
> +                reject(t('Incompatible NFT'));
Update error message

2024-10-02 03:20 UTC, nampc1 commented on packages/extension-web-ui/src/Popup/Home/Nfts/NftImport.tsx
> +                reject(t('Incompatible NFT'));
Update error message

2024-10-10 05:14 UTC, nampc1 approved these changes

2024-10-11 09:09 UTC, merged