[Issue-3745] - Update message in case perform Liquid staking have XCM
Koniverse/SubWallet-Extension pull request #3800
Opened 2024-10-23 03:16 UTC by tunghp2002

2024-10-23 03:28 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3800--sw-web-runner.netlify.app

2024-10-31 11:07 UTC, nampc1 approved these changes

2024-12-10 04:40 UTC, nampc1 approved these changes

2024-12-25 03:26 UTC, nampc1 requested changes

2024-12-25 03:26 UTC, nampc1 commented on packages/extension-base/src/services/earning-service/handlers/special.ts
> +      const maxXCMValue = formatNumber(preCheckBnMaxXCM.toString(), inputTokenInfo.decimals || 0);
use utils

2024-12-25 03:26 UTC, nampc1 commented on packages/extension-base/src/services/earning-service/handlers/special.ts
> +        errorMessage: `You need at least ${parsedMinJoinPool} ${inputTokenInfo.symbol} (${originChain.name}) or ${parsedMinAltJoinPool} ${altInputTokenInfo.symbol} (${altChain.name}) to start earning
use utils to get symbol, decimals,... don't access ChainAsset's fields directly

2024-12-25 03:26 UTC, nampc1 commented on packages/extension-base/src/services/earning-service/handlers/special.ts
> +    const existentialDeposit = new BN(altInputTokenInfo.minAmount || '0');
use utils

2024-12-25 03:26 UTC, nampc1 commented on packages/extension-base/src/services/earning-service/handlers/special.ts
>        const maxValue = formatNumber(maxBn.toString(), inputTokenInfo.decimals || 0);
use utils

2025-01-10 04:54 UTC, merged