[Issue-3070] Refactor logic parsing data from contract response
Koniverse/SubWallet-Extension pull request #3812
Opened 2024-10-26 05:14 UTC by PDTnhah

2024-10-26 08:15 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3812--sw-web-runner.netlify.app

2024-10-26 10:10 UTC, bluezdot requested changes

2024-10-28 04:07 UTC, nampc1 approved these changes

2024-10-29 04:45 UTC, saltict approved these changes

2024-10-29 04:45 UTC, merged