[Issue-3801] Webapp - Integrate off-ramp
Koniverse/SubWallet-Extension pull request #3819
Opened 2024-10-29 04:18 UTC by tunghp2002

2024-10-31 07:34 UTC, nampc1 commented on packages/extension-base/src/services/chain-service/index.ts
> +  public getAssetByChainAndSymbol (chainSlug: string, symbol: string) {
isn't guaranteed to receive a unique asset

2024-10-31 13:46 UTC, S2kael requested changes

2024-11-06 09:20 UTC, S2kael requested changes

2024-11-06 09:20 UTC, S2kael commented on packages/extension-web-ui/src/Popup/Home/Tokens/index.tsx
> +  const accounts = useSelector((state: RootState) => state.accountState.accounts);
Remove unused code

2024-11-06 09:20 UTC, S2kael commented on packages/extension-web-ui/src/Popup/BuyTokens.tsx
> +            onClick={handleBuyForm}
Convert a `useCallback` function

2024-11-06 09:20 UTC, S2kael commented on packages/extension-web-ui/src/Popup/BuyTokens.tsx
> +            onClick={handleSellForm}
Convert a `useCallback` function

2024-11-06 09:20 UTC, S2kael commented on packages/extension-web-ui/src/Popup/BuyTokens.tsx
> +      backgroundColor: '#1A1A1A',
Use `token.colorBgSecondary`

2024-11-06 09:20 UTC, S2kael commented on packages/extension-web-ui/src/Popup/Root.tsx
> +  useEffect(() => {
Improve performance

2024-11-06 09:20 UTC, S2kael commented on packages/extension-web-ui/src/types/buy.ts
>  export interface BuyService {
Remove unnecessary interface (duplicated)

2024-11-06 09:20 UTC, S2kael commented on packages/extension-web-ui/src/utils/buy/transak.ts
> +      apiKey: '307807a5-5fb3-4add-8a6c-fca4972e0470',
Rollback

2024-11-06 09:20 UTC, S2kael commented on packages/extension-web-ui/src/utils/buy/transak.ts
> +    const params: TransakOrderParams = {
Can use `Record<string, string | number | boolean | null>` instead

2024-11-07 05:20 UTC, S2kael approved these changes

2024-11-07 08:13 UTC, merged