[Issue-3826] Support Unified bridge on Polygon
Koniverse/SubWallet-Extension pull request #3833
Opened 2024-11-05 13:41 UTC by S2kael

### Related issue(s)

- #3826

### Is your feature request related to a problem(s)? Please describe.

- Init Polygon bridge

### Describe the solution you'd like

- Init Polygon bridge

### Describe alternatives you've considered

- No

### Additional context

- No

2024-11-05 13:51 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3833--sw-web-runner.netlify.app

2024-11-18 12:00 UTC, bluezdot requested changes

2024-11-18 12:00 UTC, bluezdot commented on packages/extension-base/src/services/balance-service/transfer/xcm/polygonBridge.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unsafe-call,@typescript-eslint/no-unsafe-member-access,@typescript-eslint/no-unsafe-assignment
Must check to handle all cases. Should not ignore like this

2024-11-18 12:00 UTC, bluezdot commented on packages/extension-base/src/services/balance-service/transfer/xcm/polygonBridge.ts
> +  const isTestnet = chainSlug === 'sepolia_ethereum';
use COMMON_CHAIN_SLUGS.ETHEREUM_SEPOLIA instead of. Also check others fixed string.

2024-11-18 12:00 UTC, bluezdot commented on packages/extension-base/src/services/balance-service/transfer/xcm/polygonBridge.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unsafe-call,@typescript-eslint/no-unsafe-member-access,@typescript-eslint/no-unsafe-assignment
Must check to handle all cases. Should not ignore like this

2024-11-18 12:00 UTC, bluezdot commented on packages/extension-base/src/background/KoniTypes.ts
> +  [ExtrinsicType.CLAIM_AVAIL_BRIDGE]: RequestClaimBridge
Check if should split into 2 extrinsic

2024-11-20 12:03 UTC, nampc1 approved these changes

2024-11-21 05:03 UTC, S2kael commented on packages/extension-base/src/services/balance-service/transfer/xcm/polygonBridge.ts
> +  const priority = await calculateGasFeeParams(evmApi, evmApi.chainSlug);
No handle gas fee for zk?

2024-11-21 05:06 UTC, S2kael commented on packages/extension-base/src/services/inapp-notification-service/utils/polygon.ts
> +          'x-api-key': 'polygonag_4RFN-g_wt2o12GmK9WWOWrGf-4Hamhtd'
Where is the source of this api key?

2024-11-21 05:15 UTC, S2kael commented on packages/extension-base/src/services/inapp-notification-service/index.ts
> +  // @ts-ignore
Remove this line

2024-11-21 05:25 UTC, S2kael commented on packages/extension-base/src/services/inapp-notification-service/index.ts
> +    const etherChains = [COMMON_ASSETS.ETH, COMMON_ASSETS.ETH_SEPOLIA];
Not handle for case L1 -> L2. With the result of `fetchPolygonBridgeTransactions`, have any case return data of L1 -> L2?

2024-11-21 05:27 UTC, S2kael commented on packages/extension-base/src/services/inapp-notification-service/interfaces.ts
> +  polygonBridgeClaim: boolean, // notice when an account has an avail bridge to claim
Update comment, replace `avail` to `polygon`

2024-11-21 05:29 UTC, S2kael commented on package.json
> +    "@subwallet/chain-list": "0.2.94-beta.0",
Merge from `subwallet-dev` and update asset ref on chain list before release

2024-11-21 05:31 UTC, S2kael commented on packages/extension-base/src/types/avail-bridge/index.ts
> +export interface RequestClaimBridge {
Rename folder and add export to `types/index`

2024-11-21 05:33 UTC, S2kael commented on packages/extension-koni-ui/src/Popup/Confirmations/variants/Transaction/variants/ClaimBridge.tsx
> +  const isPolygonBridge = (data.notification?.actionType === 'CLAIM_POLYGON_BRIDGE');
Move into `useMemo`

2024-11-21 05:35 UTC, S2kael commented on packages/extension-koni-ui/src/Popup/Transaction/variants/ClaimBridge.tsx
> +  const isPolygonBridge = (notification?.actionType === 'CLAIM_POLYGON_BRIDGE');
Add to `useMemo`

2024-11-21 12:34 UTC, S2kael commented on packages/extension-base/src/services/fee-service/utils/index.ts
> +      const isTestnet = networkKey === 'polygonzkEvm_cardona';
Is it necessary to use gas indexer of polygon?
Maybe use the fallback of this function?

2024-11-21 12:34 UTC, S2kael commented on packages/extension-base/src/services/fee-service/utils/index.ts
> +      const isTestnet = networkKey === 'polygonzkEvm_cardona';
Move this code to the header of try

2024-11-21 12:34 UTC, S2kael commented on packages/extension-base/src/services/migration-service/scripts/MigrateTransactionHistoryBridge.ts
> +      const claimAvailBridgeTransactions = oldTransactionData.filter((item) => item.type === ExtrinsicType.CLAIM_AVAIL_BRIDGE);
Remove this extrinsic type, use constant string instead to avoid build error

2024-11-21 12:34 UTC, S2kael commented on packages/extension-base/src/services/migration-service/scripts/MigrateTransactionHistoryBridge.ts
> +        await state.historyService.updateHistoryByExtrinsicHash(newItem.extrinsicHash, newItem);
Not to update full data with `updateHistoryByExtrinsicHash`

2024-11-21 12:34 UTC, S2kael commented on packages/extension-base/src/services/inapp-notification-service/interfaces.ts
> +  HAVE_TO_WAIT_POLYGON_BRIDGE_L2_TO_L1 = 'HAVE_TO_WAIT_POLYGON_BRIDGE_L2_TO_L1',
Remove deprecated value to avoid build error

2024-11-21 12:34 UTC, S2kael commented on packages/extension-base/src/services/migration-service/scripts/index.ts
> +  '1.3.6-07': MigrateTransactionHistoryBridge
Rollback last number to 01

2024-11-22 03:43 UTC, S2kael commented on packages/extension-base/src/services/inapp-notification-service/index.ts
> +    const etherChains = [COMMON_ASSETS.ETH, COMMON_ASSETS.ETH_SEPOLIA];
No data with status `READY_TO_CLAIM` on case bridge from L1 -> L2

2024-11-27 12:29 UTC, merged