[Issue 3855] Support swap TAO on SimpleSwap
Koniverse/SubWallet-Extension pull request #3871
Opened 2024-11-26 04:57 UTC by tunghp2002

2024-11-26 05:08 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3871--sw-web-runner.netlify.app

2024-11-26 10:03 UTC, nampc1 requested changes

2024-11-26 10:03 UTC, nampc1 commented on packages/extension-base/src/services/swap-service/handler/simpleswap-handler.ts
> +      const fromAsset = this.chainService.getAssetBySlug(request.pair.from);
also need to validate token info and swap pair key on SimpleSwap

2024-12-03 05:07 UTC, nampc1 requested changes

2024-12-03 12:20 UTC, nampc1 approved these changes

2024-12-06 11:41 UTC, S2kael commented on packages/extension-koni-ui/src/Popup/Transaction/variants/Swap.tsx
> +    setCurrentQuoteRequest(currentRequest);
use this code instead

```typescript
    setCurrentQuoteRequest((oldRequest) => {
      if (!oldRequest) {
        return undefined
      }
      
      return {
        ...oldRequest,
        currentQuote: quote.provider
      };
    })
```

2024-12-17 05:16 UTC, S2kael commented on packages/extension-web-ui/src/Popup/Transaction/variants/Swap.tsx
> +      return currentSlippage.slippage;
Make a simple logic

2024-12-18 05:53 UTC, merged