[Issue-3920] Show well-known tokens on top
Koniverse/SubWallet-Extension pull request #3934
Opened 2024-12-18 09:02 UTC by PDTnhah

2024-12-18 09:25 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3934--sw-web-runner.netlify.app

2024-12-19 05:14 UTC, nampc1 approved these changes

2025-01-02 08:40 UTC, nampc1 requested changes

2025-01-02 08:40 UTC, nampc1 commented on packages/extension-base/src/background/KoniTypes.ts
> +  piority: number
wrong spelling

2025-01-02 08:40 UTC, nampc1 commented on packages/extension-koni-ui/src/contexts/DataContext.tsx
> +  _DataContext.addHandler({ ...subscribePopularTokens, name: 'subscribePopularTokens', relatedStores: ['chainStore'], isStartImmediately: true });
is it necessary to start immediately?

2025-01-02 08:40 UTC, nampc1 commented on packages/extension-koni-ui/src/utils/sort/token.ts
> +  if (aIsPiorityToken && !bIsPiorityToken) {
wrong spelling

2025-01-02 10:46 UTC, lw-cdm commented on packages/extension-koni-ui/src/components/Modal/ReceiveModalNew/parts/TokenSelector.tsx
> +      return sortTokenInGetAddressScreen(filteredList, popularTokens);
recheck this

2025-01-02 10:50 UTC, lw-cdm commented on packages/extension-koni-ui/src/utils/sort/token.ts
> +  return tokenGroupSlug.sort((a, b) => {
find a way top group sortToken and sortTokenInGetAddressScreen into one

2025-01-06 09:10 UTC, lw-cdm commented on packages/extension-koni-ui/src/utils/sort/token.ts
> +export const sortByTokenPopularity = (a: string, b: string, aIsPiorityToken: boolean, bIsPiorityToken: boolean, aPiority: number, bPiority: number): number => {
recheck spelling (Piority -> Priority)

2025-01-06 09:21 UTC, lw-cdm commented on packages/extension-base/src/background/KoniTypes.ts
> +export interface PopularGroup {
Rename the type to make them more meaningful and grammatically correct

2025-01-06 09:23 UTC, lw-cdm commented on packages/extension-base/src/background/KoniTypes.ts
> +  'pri(popular.tokens)': [null, Record<string, PopularGroup>, Record<string, PopularGroup>];
Rename the type

2025-01-06 09:24 UTC, lw-cdm commented on packages/extension-koni-ui/src/components/Modal/ReceiveModalNew/parts/TokenSelector.tsx
> +    } else if (currentSearchText.toLowerCase() === '') {
Recheck this logic

2025-01-06 09:28 UTC, lw-cdm commented on packages/extension-koni-ui/src/utils/sort/token.ts
> +    const aPiority = a.multiChainAsset ? aIsPiorityToken ? (popularTokens[a.multiChainAsset].tokens)[a.slug] : 0 : aIsPiorityToken ? popularTokens[a.slug].piority : 0;
Recheck spelling

2025-02-11 04:55 UTC, merged