[Issue 3306] Update signing flow with metadata
Koniverse/SubWallet-Extension pull request #3937
Opened 2024-12-19 02:42 UTC by tunghp2002

2024-12-19 02:52 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: ff9ab2ed436066345be58678c2ee553ef5ebeb7c15943846cebace345458b4af -->
🚀 Deployed on https://pr-3937--sw-web-runner.netlify.app

2024-12-20 08:15 UTC, S2kael requested changes

2024-12-20 08:15 UTC, S2kael commented on packages/extension-base/src/koni/background/handlers/Extension.ts
> +        { metadata: this.#koniState.getSubstrateApi(chainInfo?.slug ?? '').metadata, source: MetadataSource.API },
This metadata not updated after connect with chain

2024-12-20 08:15 UTC, S2kael commented on packages/extension-base/src/koni/background/handlers/Extension.ts
> +      const [apiMetadata, dbMetadata, dappMetadata] = await Promise.all([
Change to get registry

2024-12-23 10:40 UTC, S2kael requested changes

2024-12-23 10:40 UTC, S2kael commented on packages/extension-base/src/koni/background/utils.ts
> +    ss58Format: metadata.tokenInfo?.ss58Format,
Simple with `metadata.tokenInfo`

2024-12-23 10:40 UTC, S2kael commented on packages/extension-base/src/utils/metadata.ts
> +    await getMetadata(chain, api, chainService);
Use `.then.catch` instead

2024-12-24 03:28 UTC, S2kael requested changes

2024-12-24 03:28 UTC, S2kael commented on packages/extension-base/src/utils/metadata.ts
> +    return updateMetadata(chain, api, chainService)
Split 2 line:
```
updateMetadata.then.catch
updateMetadataV15.then.catch
```

2025-01-10 04:21 UTC, merged